### ISSUE TITLE
 dependencies installation issue: failed to build wheel for msgspec

### ISSUE THREAD

**Issue by alex-l637** [octopize/octopize-linkage#17]
### my environment 

ProductName:            macOS
ProductVersion:         14.6.1
BuildVersion:           23G93
Python 3.13.0
pip 24.2 from /opt/homebrew/lib/python3.13/site-packages/pip (python 3.13)
git version 2.39.3 (Apple Git-146)

### steps to reproduce the error 
1. ```poetry lock```
2. ```poetry install```

### error msg 

Installing dependencies from lock file

Package operations: 5 installs, 0 updates, 0 removals

  - Installing msgspec (0.18.6)

  ChefBuildError

  Backend subprocess exited when trying to invoke build_wheel
  
  running bdist_wheel
  running build
  running build_py
  creating build/lib.macosx-14.0-arm64-cpython-313/msgspec
  copying msgspec/msgpack.py -> build/lib.macosx-14.0-arm64-cpython-313/msgspec
  copying msgspec/_version.py -> build/lib.macosx-14.0-arm64-cpython-313/msgspec
  copying msgspec/__init__.py -> build/lib.macosx-14.0-arm64-cpython-313/msgspec
  copying msgspec/yaml.py -> build/lib.macosx-14.0-arm64-cpython-313/msgspec
  copying msgspec/structs.py -> build/lib.macosx-14.0-arm64-cpython-313/msgspec
  copying msgspec/inspect.py -> build/lib.macosx-14.0-arm64-cpython-313/msgspec
  copying msgspec/_json_schema.py -> build/lib.macosx-14.0-arm64-cpython-313/msgspec
  copying msgspec/json.py -> build/lib.macosx-14.0-arm64-cpython-313/msgspec
  copying msgspec/_utils.py -> build/lib.macosx-14.0-arm64-cpython-313/msgspec
  copying msgspec/toml.py -> build/lib.macosx-14.0-arm64-cpython-313/msgspec
  copying msgspec/msgpack.pyi -> build/lib.macosx-14.0-arm64-cpython-313/msgspec
  copying msgspec/__init__.pyi -> build/lib.macosx-14.0-arm64-cpython-313/msgspec
  copying msgspec/json.pyi -> build/lib.macosx-14.0-arm64-cpython-313/msgspec
  copying msgspec/structs.pyi -> build/lib.macosx-14.0-arm64-cpython-313/msgspec
  copying msgspec/py.typed -> build/lib.macosx-14.0-arm64-cpython-313/msgspec
  UPDATING build/lib.macosx-14.0-arm64-cpython-313/msgspec/_version.py
  set build/lib.macosx-14.0-arm64-cpython-313/msgspec/_version.py to '0.18.6'
  running build_ext
  building 'msgspec._core' extension
  creating build/temp.macosx-14.0-arm64-cpython-313/msgspec
  clang -fno-strict-overflow -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -O3 -Wall -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk -I/private/var/folders/_f/fzv_0lpd723cqb8y0sbpnpjm0000gn/T/tmpkk2840ux/.venv/include -I/opt/homebrew/opt/python@3.13/Frameworks/Python.framework/Versions/3.13/include/python3.13 -c msgspec/_core.c -o build/temp.macosx-14.0-arm64-cpython-313/msgspec/_core.o
  msgspec/_core.c:500:13: error: call to undeclared function '_PyUnicode_EQ'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
          if (_PyUnicode_EQ(kwname, key)) {
              ^
  msgspec/_core.c:4452:12: error: call to undeclared function '_PySet_NextEntry'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
      while (_PySet_NextEntry(state->structs_set, &set_pos, &set_item, &set_hash)) {
             ^
  msgspec/_core.c:7316:17: error: call to undeclared function '_PyUnicode_EQ'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
              if (_PyUnicode_EQ(kwname, field)) {
                  ^
  msgspec/_core.c:7723:17: error: call to undeclared function '_PyUnicode_EQ'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
              if (_PyUnicode_EQ(kwname, field)) goto kw_found;
                  ^
  msgspec/_core.c:11254:72: error: too few arguments to function call, expected 6, have 5
      int out = _PyLong_AsByteArray((PyLongObject *)int128, buf, 16, 0, 0);
                ~~~~~~~~~~~~~~~~~~~                                      ^
  /opt/homebrew/opt/python@3.13/Frameworks/Python.framework/Versions/3.13/include/python3.13/cpython/longobject.h:111:17: note: '_PyLong_AsByteArray' declared here
  PyAPI_FUNC(int) _PyLong_AsByteArray(PyLongObject* v,
                  ^
  msgspec/_core.c:12426:12: error: call to undeclared function '_PySet_NextEntry'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
      while (_PySet_NextEntry(obj, &ppos, &item, &hash)) {
             ^
  msgspec/_core.c:13748:12: error: call to undeclared function '_PySet_NextEntry'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
      while (_PySet_NextEntry(obj, &ppos, &item, &hash)) {
             ^
  7 errors generated.
  error: command '/usr/bin/clang' failed with exit code 1
  

  at /opt/homebrew/Cellar/poetry/1.8.4/libexec/lib/python3.13/site-packages/poetry/installation/chef.py:164 in _prepare
      160│ 
      161│                 error = ChefBuildError("\n\n".join(message_parts))
      162│ 
      163│             if error is not None:
    → 164│                 raise error from None
      165│ 
      166│             return path
      167│ 
      168│     def _prepare_sdist(self, archive: Path, destination: Path | None = None) -> Path:

Note: This error originates from the build backend, and is likely not a problem with poetry but with msgspec (0.18.6) not supporting PEP 517 builds. You can verify this by running 'pip wheel --no-cache-dir --use-pep517 "msgspec (==0.18.6)"'.



### additional info
- I tried to install ```msgspec``` but still failed to build the wheel
```pip3 wheel --no-cache-dir --use-pep517 "msgspec (==0.18.6)"```

**Comment by olivierabz** [comment]
@b-rodrigues to setup nix for dependencies management

**Comment by b-rodrigues** [comment]
I think we can close this now
